databases:
  - name: Ecommerce_projectdb
    plan: free
    databaseName: Ecommerce_project
    user: cv

services:
  - type: web
    plan: free
    name: Ecommerce_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Ecommerce_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
