# Generated by Django 5.0.6 on 2024-06-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=30)),
                ("descrizione", models.TextField()),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=7)),
                ("disponibile", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ordine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ordine", models.DateTimeField(auto_now_add=True)),
                ("indirizzo_spedizione", models.CharField(max_length=100)),
                (
                    "stato_ordine",
                    models.CharField(
                        choices=[
                            ("IN_ATTESA", "In Attesa"),
                            ("IN_TRANSITO", "In Transito"),
                            ("CONSEGNATO", "Consegnato"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metodo_pagamento", models.CharField(max_length=20)),
                (
                    "numero_tracciamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("note_aggiuntive", models.TextField(blank=True, null=True)),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DettaglioOrdine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita", models.PositiveIntegerField()),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ordine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.ordine",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.prodotto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfiloUtente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indirizzo_di_spedizione", models.CharField(max_length=50)),
                ("informazioni_di_pagamento", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Taglia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taglia", models.CharField(max_length=4)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.prodotto",
                    ),
                ),
            ],
        ),
    ]
