# Generated by Django 5.0.6 on 2024-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dettaglioordine",
            options={"verbose_name_plural": "DettagliOrdini"},
        ),
        migrations.AlterModelOptions(
            name="ordine",
            options={"verbose_name_plural": "Ordini"},
        ),
        migrations.AlterModelOptions(
            name="prodotto",
            options={"verbose_name_plural": "Prodotti"},
        ),
        migrations.AlterModelOptions(
            name="profiloutente",
            options={"verbose_name_plural": "ProfiliUtenti"},
        ),
        migrations.AlterModelOptions(
            name="taglia",
            options={"verbose_name_plural": "Taglie"},
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="descrizione",
            field=models.TextField(blank=True, null=True),
        ),
    ]
