# Generated by Django 5.0.6 on 2024-06-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_rename_profiloutente_utente_alter_utente_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utente",
            name="user",
        ),
        migrations.AddField(
            model_name="utente",
            name="cognome",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="utente",
            name="data_di_registrazione",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="email",
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="nome",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="utente",
            name="username",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="ordine",
            name="utente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecommerce.utente"
            ),
        ),
    ]
