# Generated by Django 5.0.6 on 2024-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_remove_utente_user_utente_cognome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="immagine",
            field=models.ImageField(
                default="https://placehold.co/600x400", upload_to="prodotti"
            ),
        ),
    ]
