# Generated by Django 5.0.6 on 2024-06-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_prodotto_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="immagine",
            field=models.ImageField(
                default="https://placehold.co/500x300", upload_to="prodotti"
            ),
        ),
    ]
