# Generated by Django 5.0.6 on 2024-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_alter_prodotto_immagine"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="sesso",
            field=models.CharField(
                choices=[("M", "m"), ("F", "f"), ("UNISEX", "unisex")],
                default="UNISEX",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ABBIGLIAMENTO", "abbigliamento"),
                    ("SCARPE", "scarpe"),
                    ("PROFUMO", "profumo"),
                    ("ACESSORIO", "accessorio"),
                ],
                default="ABBIGLIAMENTO",
                max_length=30,
            ),
        ),
    ]
