# Generated by Django 5.0.6 on 2024-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_alter_prodotto_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ABBIGLIAMENTO", "abbigliamento"),
                    ("SCARPE", "scarpe"),
                    ("PROFUMO", "profumo"),
                    ("ACCESSORIO", "accessorio"),
                ],
                default="ABBIGLIAMENTO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("MAGLIA", "maglia"),
                    ("CAMICIA", "camicia"),
                    ("PANTALONE", "pantalone"),
                    ("GIUBBOTTO", "giubbotto"),
                ],
                default="MAGLIA",
                max_length=30,
            ),
        ),
    ]
