# Generated by Django 5.0.6 on 2024-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0013_taglia_quantità"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taglia",
            name="taglia",
            field=models.CharField(
                choices=[
                    ("XS", "xs"),
                    ("S", "s"),
                    ("M", "m"),
                    ("L", "l"),
                    ("XL", "xl"),
                ],
                default="M",
                max_length=4,
            ),
        ),
    ]
