# Generated by Django 5.0.6 on 2024-06-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0014_alter_taglia_taglia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prodotto",
            name="tipo",
        ),
        migrations.CreateModel(
            name="ProdottoScarpe",
            fields=[
                (
                    "prodotto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.prodotto",
                    ),
                ),
                ("numero", models.CharField(max_length=4)),
            ],
            bases=("ecommerce.prodotto",),
        ),
        migrations.RemoveField(
            model_name="prodotto",
            name="disponibile",
        ),
        migrations.RemoveField(
            model_name="taglia",
            name="taglia",
        ),
        migrations.CreateModel(
            name="ProdottoAbbigliamento",
            fields=[
                (
                    "prodotto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.prodotto",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MAGLIA", "MAGLIA"),
                            ("CAMICIA", "CAMICIA"),
                            ("FELPA", "FELPA"),
                            ("PANTALONE", "PANTALONE"),
                            ("GIUBBOTTO", "GIUBBOTTO"),
                        ],
                        max_length=30,
                    ),
                ),
                ("taglia_abbigliamento", models.CharField(max_length=4)),
            ],
            bases=("ecommerce.prodotto",),
        ),
        migrations.AlterField(
            model_name="taglia",
            name="prodotto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce.prodottoabbigliamento",
            ),
        ),
    ]
