# Generated by Django 5.0.6 on 2024-06-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0015_remove_prodotto_tipo_prodottoscarpe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taglia",
            name="prodotto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taglie",
                to="ecommerce.prodotto",
            ),
        ),
        migrations.RemoveField(
            model_name="prodottoscarpe",
            name="prodotto_ptr",
        ),
        migrations.AddField(
            model_name="taglia",
            name="taglia",
            field=models.CharField(
                choices=[
                    ("XS", "xs"),
                    ("S", "s"),
                    ("M", "m"),
                    ("L", "l"),
                    ("XL", "xl"),
                ],
                default="M",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ProdottoAbbigliamento",
        ),
        migrations.DeleteModel(
            name="ProdottoScarpe",
        ),
    ]
