# Generated by Django 5.0.6 on 2024-06-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0018_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numero",
            name="prodotto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="numeri",
                to="ecommerce.prodotto",
            ),
        ),
    ]
