# Generated by Django 5.0.6 on 2024-06-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0019_alter_numero_prodotto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Numero",
        ),
    ]
