# Generated by Django 5.0.6 on 2024-06-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0020_delete_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        choices=[
                            ("36,5", "36,5"),
                            ("37", "37"),
                            ("37,5", "37,5"),
                            ("38", "38"),
                            ("38,5", "38,5"),
                            ("39", "39"),
                            ("39,5", "39,5"),
                            ("40", "40"),
                            ("40,5", "40,5"),
                            ("41", "41"),
                            ("41,5", "41,5"),
                            ("42", "42"),
                            ("42,5", "42,5"),
                            ("43", "43"),
                            ("43,5", "43,5"),
                            ("44", "44"),
                        ],
                        default="40",
                        max_length=30,
                    ),
                ),
                (
                    "quantità",
                    models.DecimalField(decimal_places=0, default=1, max_digits=7),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeri",
                        to="ecommerce.prodotto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Numeri",
            },
        ),
    ]
