# Generated by Django 5.0.6 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0023_delete_giorni"),
    ]

    operations = [
        migrations.AddField(
            model_name="taglia",
            name="numero",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="taglia",
            name="quantità",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Numero",
        ),
    ]
