# Generated by Django 5.0.6 on 2024-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0024_taglia_numero_alter_taglia_quantità_delete_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taglia",
            name="quantità",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="taglia",
            name="taglia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "xs"),
                    ("S", "s"),
                    ("M", "m"),
                    ("L", "l"),
                    ("XL", "xl"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
