# Generated by Django 5.0.6 on 2024-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0025_alter_taglia_quantità_alter_taglia_taglia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taglia",
            name="quantità",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
