# Generated by Django 5.0.6 on 2024-06-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0027_carrello"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrello",
            name="utente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrello",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
