# Generated by Django 5.0.6 on 2024-06-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0028_alter_carrello_utente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrello",
            name="utente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrello",
                to="ecommerce.utente",
            ),
        ),
    ]
