# Generated by Django 5.0.6 on 2024-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0030_alter_ordine_utente_alter_carrello_utente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrello",
            name="immagine",
            field=models.ImageField(
                default="https://placehold.co/600x400", upload_to="prodotti"
            ),
        ),
    ]
