# Generated by Django 5.0.6 on 2024-06-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0031_carrello_immagine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrello",
            name="immagine",
        ),
    ]
