# Generated by Django 5.0.6 on 2024-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0032_remove_carrello_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordine",
            name="stato_ordine",
            field=models.CharField(
                choices=[
                    ("IN_ATTESA", "In Attesa"),
                    ("IN_TRANSITO", "In Transito"),
                    ("CONSEGNATO", "Consegnato"),
                    ("ANNULLATO", "annullato"),
                ],
                max_length=20,
            ),
        ),
    ]
