# Generated by Django 5.0.6 on 2024-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0033_alter_ordine_stato_ordine"),
    ]

    operations = [
        migrations.AddField(
            model_name="dettaglioordine",
            name="numero",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="dettaglioordine",
            name="taglia",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
